maintainer : streambinder
name       : pantheon-music
version    : 5.0.5
release    : 3
source     :
    - https://github.com/elementary/music/archive/5.0.5.tar.gz : ed7cba3b07189273890b321b21cda198f18b102e4466eb7207c0b5f27b31dfc9
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon music app
description: |
    Desktop music app designed for elementary OS.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(libgda-5.0)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsignon-glib)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(taglib)
    - pkgconfig(zeitgeist-2.0)
    - glib2-devel
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
