maintainer : streambinder
name       : gala
version    : 3.3.2
release    : 10
source     :
    - https://github.com/elementary/gala/archive/c74298b49c3d3be2ff3df5d7f6990d8d7fea52f6.tar.gz : cc7ae8a36b460addde9b2e3f70ee64f8733b1ba2afc5cdef16727bf07f2ecb09
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon window and compositing manager
description: |
    A window and compositing manager based on libmutter and designed by elementary for use with Pantheon.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(clutter-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(granite)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libmutter-7)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - gettext-devel
    - glib2-devel
    - gsettings-desktop-schemas-devel
    - pantheon-dock-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
