maintainer : streambinder
name       : pantheon-onboarding
version    : 1.2.1
release    : 6
source     :
    - https://github.com/elementary/onboarding/archive/1.2.1.tar.gz : 37edf0d48004b9e061e7998c899f44f3df4dc0848b9c362b368c73c84177d988
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon onboarding app
description: |
    Onboarding app designed for elementary OS.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
