maintainer : algent-al
name       : youtube-dlg
version    : 0.4
release    : 2
source     :
    - https://github.com/MrS0m30n3/youtube-dl-gui/archive/0.4.tar.gz : 70d7729a51a463f8b4d05e765681cff8f7444282ab5f29a4b71cc2f0fba00065
homepage   : https://mrs0m30n3.github.io/youtube-dl-gui/
license    : Unlicense
component  : network.download
summary    : youtube-dlg (or youtube-dl-gui), is a GUI of the popular youtube-dl.
description: |
    youtube-dlg (or youtube-dl-gui) is a cross platform front-end GUI of the popular youtube-dl written in wxPython.
builddeps  :
    - pkgconfig(libavformat)
    - python2-twodict
    - wxPython-devel
rundeps    :
    - wxPython
    - python2-twodict
build      : |
    %python_setup
install    : |
    %python_install
    install -Dm00644 $pkgfiles/youtube-dl-gui.desktop $installdir/usr/share/applications/youtube-dl-gui.desktop

    #install manpage
    install -Dm00644 $pkgfiles/youtube-dl-gui.1 $installdir/usr/share/man/man1/youtube-dl-gui.1
