maintainer : algent-al
name       : python-cairosvg
version    : 2.4.2
release    : 1
source     :
    - https://github.com/Kozea/CairoSVG/archive/2.4.2.tar.gz : ae988993f8e3e79f8da1cc6fe4f16f9b3f4b7e174c19f5ab61444564bf003086
homepage   : https://cairosvg.org/
license    : LGPL-3.0-or-later
component  : programming.python
summary    : CairoSVG is a SVG converter based on Cairo
description: |
    CairoSVG is a SVG converter based on Cairo. It can export SVG files to PDF, PostScript and PNG files.
builddeps  :
    - pytest-runner
    - pytest-isort
    - python-cairocffi
    - python-cssselect2
    - python-defusedxml
    - python-pillow
    - python-pytest-cov
    - python-pytest-flake8
rundeps    :
    - python-cairocffi
    - python-cssselect2
    - python-defusedxml
    - python-pillow
setup      : |
    cp -r cairosvg test_non_regression/cairosvg_reference/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
