name       : pdfarranger
version    : 1.5.2
release    : 4
source     :
    - https://github.com/jeromerobert/pdfarranger/archive/1.5.2.tar.gz : 9086299eeedf7e3cdf8518b1505d05e67fe4db987274f6cb0b86a2308ae46e37
homepage   : https://github.com/jeromerobert/pdfarranger
license    : GPL-3.0-or-later
component  : office
summary    : Small application to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface
description: |
    pdfarranger is a small python-gtk application, which helps the user to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface. It is a frontend for python-pyPdf
builddeps  :
    - python-distutils-extra
rundeps    :
    - poppler
    - python-pikepdf
    - python3-cairo
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
