maintainer : Justin
name       : xfce4-appfinder
version    : 4.16.1
release    : 7
source     :
    - http://archive.xfce.org/src/xfce/xfce4-appfinder/4.16/xfce4-appfinder-4.16.1.tar.bz2 : bfe3e9bd92695014ee74a2fbb7f5fd1b4c29cf043c4a11598b8958324c81e7ec
license    : GPL-2.0
component  : desktop.xfce
summary    : Xfce aplication launcher and finder
description: |
    The Application Finder is a program to find and launch installed applications on your system, and quickly execute commands.
builddeps  :
    - pkgconfig(garcon-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxfce4ui-2)
    - libxfce4util-devel
    - libxfce4util-vapi
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
