maintainer : Justin
name       : exo
version    : 4.16.0
release    : 6
source     :
    - https://archive.xfce.org/src/xfce/exo/4.16/exo-4.16.0.tar.bz2 : 1975b00eed9a8aa1f899eab2efaea593731c19138b83fdff2f13bdca5275bacc
license    : GPL-2.0
component  : desktop.xfce
summary    : Application library for the Xfce desktop environment
description: |
    libexo is an extension library to Xfce, originally developed by os-cillation.
    While Xfce comes with quite a few libraries that are targeted at desktop development, libexo is targeted at application development.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxfce4ui-2)
    - libxfce4util-devel
    - gtk-doc
    - perl-uri
    - xfce4-dev-tools
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
