maintainer : Justin
name       : thunar
version    : 4.17.0
release    : 9
source     :
    - https://archive.xfce.org/src/xfce/thunar/4.17/thunar-4.17.0.tar.bz2 : ad004f02d8bda692d76ec2a264e3e1121ae065f3d2ecc9cfe7dd82cd5c69f8a5
license    : GPL-2.0
component  : desktop.xfce
summary    : Thunar File Manager
description: |
    Thunar is a modern file manager for the Unix/Linux desktop, aiming to be easy-to-use and fast.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libxfce4panel-2.0) 
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(x11)
    - gtk-doc
    - xfce4-dev-tools
rundeps    :
    - gvfs
    - tumbler
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
