maintainer : algent-al
name       : python-pikepdf
version    : 1.14.0
release    : 5
source     :
    - https://github.com/pikepdf/pikepdf/archive/v1.14.0.tar.gz : e94c5c43f16db23d86933b738e208b2ddd7cfa5ad675c6b3b0b874ff93d5a1b2
homepage   : https://github.com/pikepdf/pikepdf
license    : MPL-2.0
component  : programming.python
summary    : A Python library for reading and writing PDF, powered by qpdf
description: |
    Pikepdf is a Python library for reading and writing PDF files.
builddeps  :
    - pkgconfig(libqpdf)
    - pkgconfig(python3)
    - pybind11
    - python-setuptools-scm-git-archive
rundeps    :
    - python-lxml
build      : |
    %python3_setup
install    : |
    %python3_install
