maintainer : streambinder
name       : wingpanel-indicator-nightlight
version    : 2.0.4
release    : 5
source     :
    - https://github.com/elementary/wingpanel-indicator-nightlight/archive/2.0.4.tar.gz : f10d8e212fc46cc5cafc4d3fab8bcedd1a259fb0a686ae9ae9e145d049d93cf9
license    : GPL-2.0
component  : desktop.pantheon
summary    : Wingpanel nightlight indicator
description: |
    Wingpanel inicator for nightlight settings and informations.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(wingpanel)
    - glib2-devel
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
