maintainer : Justin
name       : notejot
version    : 2.0.0
release    : 3
source     :
    - https://github.com/lainsce/notejot/archive/2.0.0.tar.gz : f3f5211738413969a7ce863928701e5658df6e419e1ef5dc28b13fc49cbf6b5e
license    : GPL-3.0-or-later
homepage   : https://github.com/lainsce/notejot/
component  : desktop
summary    : Notesjot Sticky Notes
description: |
    Stupidly simple sticky notes applet
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gee-0.8)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
