maintainer : Justin
name       : notejot
version    : 2.5.2
release    : 3
source     :
    - https://github.com/lainsce/notejot/archive/2.5.2.tar.gz : c5e17248da0780bb93b801e850c511a077b0d18dfafcacc2369532627b5ab85d
license    : GPL-3.0-or-later
homepage   : https://github.com/lainsce/notejot/
component  : desktop
summary    : Notesjot Sticky Notes
description: |
    Stupidly simple sticky notes applet
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gee-0.8)
    - pkgconfig(libhandy-1)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
