maintainer : Justin
name       : notejot
version    : 1.6.3
release    : 2
source     :
    - https://github.com/lainsce/notejot/archive/1.6.3.tar.gz : 130814c480aa0cf6c2b91e06f865512ecf4db693cd89763eb7e6bdfbec08951d
license    : GPL-3.0-or-later
homepage   : https://github.com/lainsce/notejot/
component  : desktop
summary    : Notesjot Sticky Notes
description: |
    Stupidly simple sticky notes applet
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gee-0.8)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
