maintainer : Justin
name       : garcon
version    : 4.16.1
release    : 8
source     :
    - http://archive.xfce.org/src/xfce/garcon/4.16/garcon-4.16.1.tar.bz2 : 84914927a2c1fda167f67af26a6640630a744a22940df508aa6c752cdbd3d21d
license    :
    - LGPL-2.0
    - GFDL-1.1
component  : desktop.xfce
summary    : Xfce freedesktop.org compliant menu library
description: |
    Garcon is a freedesktop.org compliant menu implementation based on GLib and GIO.
    It was started as a complete rewrite of the former Xfce menu library called libxfce4menu, which, in contrast to garcon, was lacking menu merging features essential for loading menus modified with menu editors.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxfce4ui-2)
    - libxfce4util-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
