maintainer : streambinder
name       : switchboard-plug-bluetooth
version    : 2.3.5
release    : 8
source     :
    - https://github.com/elementary/switchboard-plug-bluetooth/archive/2.3.5.tar.gz : 0f919515537fe484ddc2c27394d357a86ccdae47a2e619ab6157e6214539f43a
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard bluetooth plug
description: |
    Bluetooth plug for Switchboard which configures bluetooth devices.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - glib2-devel
    - glibc-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
