maintainer : streambinder
name       : hydra
version    : 9.2
release    : 4
source     :
    - https://github.com/vanhauser-thc/thc-hydra/archive/v9.2.tar.gz : 1a28f064763f9144f8ec574416a56ef51c0ab1ae2276e35a89ceed4f594ec5d2
license    : AGPL-3.0
component  : security
summary    : A very fast network logon cracker which support many different services
description: |
    Hydra  is  a  parallelized  login cracker which supports numerous protocols to attack.
    New modules are easy to add, beside that, it is flexible and very fast.
    This tool gives researchers and security consultants the possibility to show how  easy it would be to gain unauthorized access from remote to a system.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
