maintainer : streambinder
name       : switchboard-plug-security-privacy
version    : 2.2.4
release    : 6
source     :
    - https://github.com/elementary/switchboard-plug-security-privacy/archive/2.2.4.tar.gz : 617c51416f1662e66d395f27d82a372196d4ccd7402e67ab158ff578ad731b9b
license    : GPL-3.0
component  : desktop.pantheon
summary    : Switchboard security and privacy plug
description: |
    Switchboard plug for managing the security and privacy of your system.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(switchboard-2.0)
    - pkgconfig(zeitgeist-2.0)
    - glib2-devel
    - glibc-devel
    - polkit-devel
    - ufw
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
