maintainer : streambinder
name       : minify
version    : 2.9.16
release    : 19
source     :
    - https://github.com/tdewolff/minify/releases/download/v2.9.16/minify_linux_amd64.tar.gz : fe1d4a4f6e80bfaeb0e8d90d828a8b5166f36e422fd44c60ec4ce05f7b125834
license    : MIT
component  : programming.tools
summary    : Go minifiers for web formats
description: |
    Minify is a minifier package written in Go.
    It provides HTML5, CSS3, JS, JSON, SVG and XML minifiers and an interface to implement any other minifier.
    Minification is the process of removing bytes from a file (such as whitespace) without changing its output and therefore shrinking its size and speeding up transmission over the internet and possibly parsing.
    The implemented minifiers are designed for high performance.
    The core functionality associates mimetypes with minification functions, allowing embedded resources (like CSS or JS within HTML files) to be minified as well.
    Users can add new implementations that are triggered based on a mimetype (or pattern), or redirect to an external command (like ClosureCompiler, UglifyCSS, ...).
setup      : |
    mkdir -p $installdir/usr/bin
install    : |
    cp -fp minify $installdir/usr/bin
