maintainer : algent-al
name       : pytest-isort
version    : 1.1.0
release    : 2
source     :
    - https://github.com/moccu/pytest-isort/archive/1.1.0.tar.gz : f49fbb5fbbecf74fb3fc956ecd21a879931a79a40bbba7866cad4d6aff1510d3
homepage   : https://github.com/moccu/pytest-isort
license    : BSD-3-Clause
component  : programming.python
summary    : py.test plugin to check import ordering using isort
description: |
    py.test plugin to check import ordering using isort
rundeps    :
    - python-isort
build      : |
    %python3_setup
install    : |
    %python3_install
