maintainer : streambinder
name       : binwalk
version    : 2.3.1
release    : 3
source     :
    - https://github.com/ReFirmLabs/binwalk/archive/v2.3.1.tar.gz : 7ec9d8fcb8686f4060d37e1096669e3ed8ce1194c91ad80199622448bcc01b19
license    : MIT
component  : security
summary    : Firmware Analysis Tool
description: |
    Binwalk is a fast, easy to use tool for analyzing, reverse engineering, and extracting firmware images.
rundeps    :
    - sleuthkit
install    : |
    %python_install
