maintainer : streambinder
name       : fondo
version    : 1.5.2
release    : 14
source     :
    - https://github.com/calo001/fondo/archive/1.5.2.tar.gz : 016d67f2c4d4936426ab7a8cd4d7624e32ef9e9a9143e076a2f60257c1a67c27
license    : AGPL-3.0
component  : multimedia.graphics
summary    : Wallpaper app for Gnome
description: |
    Find a variety of the most beautiful wallpapers from Unsplash.com the world’s most generous community of photographers.
    Fondo allows you to see thousands of beautiful photographs from the most recent to the one you are to looking for.
    Give a simple click on a picture to set as wallpaper, wait until the download is complete and enjoy!
    Have a simple and elegant interface, you can change from light mode to dark mode as you prefer.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
