maintainer : algent-al
name       : cronie
version    : 1.5.6
release    : 3
source     :
    - https://github.com/cronie-crond/cronie/releases/download/cronie-1.5.6/cronie-1.5.6.tar.gz : f7ad9da2869c2dc8d9a54addfab969a9753eea8fd65e6d27dd935276eb66829d
homepage   : https://github.com/cronie-crond/cronie
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-or-later
    - ISC
component  : system.utils
summary    : Cronie cron daemon project
description: |
    Cronie contains the standard UNIX daemon crond that runs specified programs at scheduled times and related tools. The source is based on the original vixie-cron and has security and configuration enhancements like the ability to use pam and SELinux.
setup      : |
    %configure \
        --sbindir=/usr/bin \
        --enable-anacron \
        --with-inotify \
        --with-pam
build      : |
    %make
install    : |
    %make_install

    chmod u+s $installdir/usr/bin/crontab
    install -d $installdir/var/spool/{ana,}cron
    install -d $installdir/etc/cron.{d,hourly,daily,weekly,monthly}

    install -Dm00644 $pkgfiles/deny     $installdir/etc/cron.deny
    install -Dm00644 $pkgfiles/pam.d    $installdir/etc/pam.d/crond
    install -Dm00644 $pkgfiles/service  $installdir/%libdir%/systemd/system/cronie.service

    install -Dm00644 contrib/anacrontab $installdir/etc/anacrontab
    install -Dm00644 contrib/0hourly    $installdir/etc/cron.d/0hourly
    install -Dm00755 contrib/0anacron   $installdir/etc/cron.hourly/0anacron
