maintainer : streambinder
name       : stemmer
version    : 2.1.0
release    : 5
source     :
    - https://github.com/snowballstem/snowball/archive/v2.1.0.tar.gz : 24ae0b28d6531190c2cd960d515ec9374d3a3d9420c4a0accdf89b7f02fc9caa
license    : BSD-3-Clause
component  : programming.tools
summary    : Snowball stemming algorithms, development kit
description: |
    Snowball is a small string processing language designed for creating stemming algorithms for use in Information Retrieval.
    The Snowball compiler translates a Snowball script into another language - currently ISO C, C#, Go, Java, Javascript, Object Pascal, Python and Rust are supported.
setup      : |
    %apply_patches
build      : |
    %make
install    : |
    mkdir -p $installdir/usr/include
    mkdir -p $installdir/usr/lib/include
    install -Dm644 {.,$installdir/usr}/include/libstemmer.h
    install -D {.,$installdir/usr/lib}/libstemmer.so.0.0.0
    ln -s libstemmer.so.0.0.0 "$installdir/usr/lib/libstemmer.so.0"
    ln -s libstemmer.so.0 "$installdir/usr/lib/libstemmer.so"
    install -Dm644 COPYING "$installdir/usr/share/licenses/libstemmer/LICENSE"
