maintainer : Justin
name       : arc-theme
version    : 20210127
release    : 4
source     :
    - https://github.com/jnsh/arc-theme/archive/20210127.tar.gz : eba3ad05cf5c0e8e03f8b3c267d2ff278fa088bbc7c1a3fceb3c48f4da00ef78
license    : GPL-3.0-or-later
summary    : Arc GTK Theme
description: |
    A flat theme with transparent elements
component  : desktop.theme
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(gtk+-3.0)
    - inkscape
    - optipng
    - sassc
rundeps    :
    - gtk2-engine-murrine
setup      : |
    ./autogen.sh --enable-metacity \
                 --disable-unity \
                 --enable-xfwm \
                 --enable-cinnamon \
                 --with-cinnamon=4.6 \
                 --with-gnome-shell=3.36 \
                 %CONFOPTS%
install    : |
    %make_install
