maintainer : Justin
name       : xfce4-whiskermenu-plugin
version    : 2.5.3
release    : 12
source     :
    - https://github.com/gottcode/xfce4-whiskermenu-plugin/archive/v2.5.3.tar.gz : 6945afc6555916e2ce6ef66bddb90912624ac1d2b45f5b234d30d1cb6397fad7
license    : GPL-2.0
component  : desktop.xfce
summary    : Alternate Xfce menu
description: |
    Whisker Menu is an alternate application launcher for Xfce. When you open
    it you are shown a list of applications you have marked as favorites. You
    can browse through all of your installed applications by clicking on the
    category buttons on the side. Top level categories make browsing fast,
    and simple to switch between. Additionally, Whisker Menu keeps a list of
    the last ten applications that you've launched from it.
    Favorites are easy to add and reorder. When browsing through your
    applications, right-click on any of them and select "Add to Favorites".
    Simply drag and drop your favorites list to arrange them to suit your
    needs. You can remove them at any time from another right-click option.
    If you're not sure exactly where a program is listed, instead of browsing
    through each category you can simply enter a search term. The search
    field is focused when opening the menu, so you can just start typing.
    Application descriptions as well as names are searched, which allows you
    to find a program by using a general word (such as "browser" to find all
    web browsers installed on your computer).
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxfce4panel-2.0)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
