maintainer : streambinder
name       : awesomewm
version    : 4.3
release    : 5
source     :
    - https://github.com/awesomeWM/awesome/archive/v4.3.tar.gz : b8a509464fb964acfc0cfaa4c689beaceb0f720de3983053d54d440158c281dd
license    : GPL-2.0
component  : desktop.awesomewm
summary    : Awesome window manager
description: |
    Awesome is a highly configurable, next generation framework window manager for X.
    It is primarily targeted at power users, developers and any people dealing with every day computing tasks and who want to have fine-grained control on their graphical environment.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(lua)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcb-util)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xkbcommon)
    - imagemagick
    - lua-lgi
setup      : |
    %apply_patches
build      : |
    %make
install    : |
    %make_install
