name       : crond
version    : 4.5
release    : 1
source     :
    - http://www.jimpryor.net/linux/releases/dcron-4.5.tar.gz : 9e50edb6f5bd8153b16bad05087d985e5153ce45cc01ae77e7f842213fb4a824
license    : GPL-2.0-or-later
component  : system.utils
summary    : crond (Dillon's lightweight cron daemon)
description: |
    crond is a cron daemon written by Matt Dillon and continued by Jim Pryor that attempts to be as minimalist as possible.
build      : |
    %make PREFIX=/usr
install    : |
    %make_install 
    install -Dm00644 $pkgfiles/root.crontab $installdir/etc/cron.d/crontab
    install -Dm00755 $pkgfiles/run-cron $installdir/usr/sbin/run-cron
