maintainer : streambinder
name       : pantheon-term
version    : 5.5.2
release    : 23
source     :
    - https://github.com/elementary/terminal/archive/5.5.2.tar.gz : 589ad0225e3a45700d95c8ead1b646f22a22c7688f647876a5329b3b4bd923cd
license    : GPL-3.0-only
component  : desktop.pantheon
summary    : A super lightweight, beautiful, and simple terminal.
description: |
    A super lightweight, beautiful, and simple terminal. It's designed to be setup with sane defaults and little to no configuration. It's just a terminal, nothing more, nothing less.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(granite)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
    - vala
setup      : |
    %meson_configure -Dubuntu-bionic-patched-vte=false
build      : |
    %ninja_build
install    : |
    %ninja_install
