maintainer : streambinder
name       : appstream
version    : 0.14.3
release    : 8
source     :
    - https://www.freedesktop.org/software/appstream/releases/AppStream-0.14.3.tar.xz : 16bf426a8f2693a45c84f437a301e560a2fb77179917c175f5ccb0bd9883e5c6
license    : GPL-2.0
component  : desktop.core
summary    : Infrastructure for distro-agnostic software-centers and universal software component metadata
networking : true
description: |
    AppStream is a cross-distro effort for enhancing the metadata available about software components in the Linux and free-software ecosystem.
    One of the project's goals is to make building software-center applications possible, and make interaction with the package sources of a distribution smarter.
    AppStream provides specifications for meta-information which is shipped by upstream projects and can be consumed by other software.
    The meta-information includes data which is interesting to display in software centers and is mainly useful for end-users, as well as descriptions about the public interfaces a software component provides, which is mainly useful for developers, 3rd-party software installers and for automatically installing missing components on a distribution, for example missing firmware or mimetype-handlers.
    Distributors provide metadata as well, which describes all components available in a software repository.
    That data is composed of the upstream-metainfo and some other sources.
    AppStream also provides specifications for things like a screenshot-service, application ratings & reviews etc.
    All parts of AppStream are distribution-agnostic, and therefore it is easily possible to build software management tools with it that work on any distribution implementing the AppStream specification.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(yaml-0.1)
    - docbook-xml
    - glib2-devel
    - gperf
    - gtk-doc
    - lmdb-devel
    - stemmer-devel
    - vala
setup      : |
    %meson_configure -Ddocs=false -Dvapi=true
build      : |
    %meson_build
install    : |
    %meson_install
