maintainer : streambinder
name       : wingpanel-indicator-network
version    : 2.2.4
release    : 6
source     :
    - https://github.com/elementary/wingpanel-indicator-network/archive/2.2.4.tar.gz : 3068101063fff99a58eefe33afe3e3abf8e330c102c981213a4478068843850b
license    : LGPL-2.1
component  : desktop.pantheon
summary    : Wingpanel network indicator
description: |
    Wingpanel inicator for network settings and informations.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(wingpanel)
    - glib2-devel
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
