maintainer : streambinder
name       : vscodium
version    : 1.54.3
release    : 37
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.54.3/codium_1.54.3-1615854707_amd64.deb : 28db75987000fd3ec005c717122155b5289f739622041ffb1c073b86c9fed4e5
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xext)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
    find -type f -name \*.desktop -exec sed -i 's|inode/directory;||g' {} \;
    chmod 0755 $installdir/usr/share/codium/chrome-sandbox
