name       : vscodium
version    : 1.45.0
release    : 18
source     :
    - https://github.com/VSCodium/vscodium/releases/download/1.45.0/codium_1.45.0-1588934730_amd64.deb : c735a68bcbd6b58f4691edfadc4303b5a91e11953e5d13e0a92e56831bcc2486
license    : MIT
component  : programming.ide
summary    : Visual Studio Code without MS branding, telemetry and licensing
description: |
    The VSCodium project exists so that you don’t have to download+build from source.
    This project includes special build scripts that clone Microsoft’s vscode repo, run the build commands, and upload the resulting binaries for you to GitHub releases.
    These binaries are licensed under the MIT license.
    Telemetry is disabled.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xext)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
setup      : |
    mkdir -p $installdir
install    : |
    cd $installdir
    tar xvf $workdir/data.tar.*
    find -type f -name \*.desktop -exec sed -i 's|inode/directory;||g' {} \;
