maintainer : Justin
name       : deepin-kwin
version    : 5.0.14.1
release    : 1
source     :
    - https://github.com/linuxdeepin/dde-kwin/archive/5.0.14.1.tar.gz : 294971ba85fb1b915727b5233f4e098716e2282ce58529f0d2587cdc579022eb
license    : GPL-3.0-or-later
component  : desktop.deepin
summary    : Deepin Kwin
description: |
    Deepin Kwin
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(dtkgui)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gsettings-qt)
    - kconfig-devel
    - kcoreaddons-devel
    - kdecoration-devel
    - ki18n-devel
    - kglobalaccel-devel
    - kwin-devel
    - kwayland-devel
    - kwindowsystem-devel
setup      : |
    %patch -p1 <$pkgfiles/109.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
