maintainer : streambinder
name       : bcc
version    : 0.19.0
release    : 7
source     :
    - https://github.com/iovisor/bcc/releases/download/v0.19.0/bcc-src-with-submodule.tar.gz : 4c41fc1a6a7ef2084b43c52c1b2e6104230ba9f31e02958416bf131d848e74e4
license    : Apache-2.0
component  : security
summary    : Tools for BPF-based Linux IO analysis, networking, monitoring, and more
description: |
  BCC is a toolkit for creating efficient kernel tracing and manipulation programs, and includes several useful tools and examples.
  It makes use of extended BPF (Berkeley Packet Filters), formally known as eBPF, a new feature that was first added to Linux 3.15.
  Much of what BCC uses requires Linux 4.1 and above.
builddeps  :
    - ethtool
    - flex
    - iperf
    - libelf-devel
    - libstdc++
    - llvm-clang-devel
    - llvm-devel
    - luajit-devel
    - ncurses-devel
    - pip
    - python-netaddr
    - zlib-devel
setup      : |
    mkdir build
    cd build
    %cmake ..
    %cmake -DPYTHON_CMD=python3 ..
build      : |
    cd build
    %make
    cd src/python
    %make
install    : |
    pushd build
    %make_install
    cd src/python
    %make_install
