maintainer : Justin
name       : xfce4-panel
version    : 4.16.1
release    : 10
source     :
    - https://archive.xfce.org/src/xfce/xfce4-panel/4.16/xfce4-panel-4.16.1.tar.bz2 : fa099bc6be6592dbb828747a473c2e1b0e7f85afd945a98002b475bb6f975991
license    : GPL-2.0
component  : desktop.xfce
summary    : Xfce's panel
description: |
    Xfce's panel.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - libxfce4util-devel
    - libxfce4util-vapi
    - gtk-doc
    - vala
    - xfce4-dev-tools
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
