maintainer : streambinder
name       : pantheon-greeter
version    : 5.0.4
release    : 15
source     :
    - https://github.com/elementary/greeter/archive/409b7f9084df3dc936754782d8ebe02b0e7e56da.tar.gz : b78608b5703b3ae8ec85b739356f052d16246dcce9e712d17b2636bd9a9e7570
license    : GPL-3.0
component  : desktop.pantheon
conflicts  :
    - slick-greeter
summary    : LightDM Greeter for Pantheon
description: |
    Pantheon Greeter is a pantheon-styled Login Screen for LightDM.
    It is elementary OS default login screen.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(liblightdm-gobject-1)
    - pkgconfig(libmutter-7)
    - pkgconfig(libvala-0.52)
    - pkgconfig(wingpanel)
    - pkgconfig(x11)
    - desktop-file-utils
    - vala
setup      : |
    %apply_patches
    %meson_configure -Dubuntu-patched-gsd=false
build      : |
    %meson_build
install    : |
    %meson_install
