maintainer : streambinder
name       : subnetcalc
version    : 2.4.18
release    : 6
source     :
    - https://github.com/dreibh/subnetcalc/archive/subnetcalc-2.4.18.tar.gz : fb977eb5336e1bcda50eb9d64def48e4a2b2d0e38b4fc11d60d1d516991bf01f
license    : GPL-3.0
component  : network.util
summary    : IP address calculator
description: |
    SubNetCalc is an IPv4/IPv6 subnet address calculator.
    For given IPv4 or IPv6 address and netmask or prefix length, it calculates network address, broadcast address, maximum number of hosts and host address range.
    Also, it prints the addresses in binary format for better understandability.
    Furthermore, it prints useful information on specific address types (e.g. type, scope, interface ID, etc.).
builddeps  :
    - valgrind
setup      : |
    ./autogen.sh --use-gcc
build      : |
    %make
install    : |
    %make_install
check      : |
    cd $workdir/src
    ./test1
