maintainer : streambinder
name       : pantheon-tweaks
version    : 0.0.1
release    : 4
source     :
    - https://github.com/pantheon-tweaks/pantheon-tweaks/archive/96ed0ce7fc5f3a25d7bf58c974491ae4b9799ac2.tar.gz : 97a57bfb8a99f5d5f7d6f7b9a798485ee49584e3f1ee25908dbe22f09349176d
license    : GPL-3.0
component  : desktop.pantheon
summary    : Pantheon customization tool
description: |
    Tweaks is a system settings panel for Pantheon desktop that lets you easily and safely customise your desktop's appearance.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(granite)
    - pkgconfig(switchboard-2.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
