maintainer : streambinder
name       : wingpanel-indicator-datetime
version    : 2.2.5
release    : 7
source     :
    - https://github.com/elementary/wingpanel-indicator-datetime/archive/2.2.5.tar.gz : 14a7b101348ac51932edd4ca753101887e12945e77810ca7c44a2650a2886d17
license    : GPL-3.0
component  : desktop.pantheon
summary    : Wingpanel date and time indicator
description: |
    Wingpanel inicator for date and time settings and informations.
builddeps  :
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(granite)
    - pkgconfig(libecal-2.0)
    - pkgconfig(libical)
    - pkgconfig(wingpanel)
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
