maintainer : streambinder
name       : wingpanel-indicator-bluetooth
version    : 2.1.6
release    : 6
source     :
    - https://github.com/elementary/wingpanel-indicator-bluetooth/archive/2.1.6.tar.gz : 52b510e04010f735221294f3b5d94372db13b040a7034e2cc3fca7d507352aea
license    : LGPL-2.1
component  : desktop.pantheon
summary    : Wingpanel bluetooth indicator
description: |
    Wingpanel inicator for bluetooth settings and informations.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(granite)
    - pkgconfig(libnotify)
    - pkgconfig(wingpanel)
    - glib2-devel
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
