maintainer : Justin
name       : xfdesktop
version    : 4.16.0
release    : 8
source     :
    - http://archive.xfce.org/src/xfce/xfdesktop/4.16/xfdesktop-4.16.0.tar.bz2 : 934ba5affecff21e62d9fac1dd50c50cd94b3a807fefa5f5bff59f3d6f155bae
license    : GPL-2.0
component  : desktop.xfce
summary    : Xfce's desktop manager
description: |
    Xfdesktop is a desktop manager for the Xfce Desktop Environment. Desktop in this respect means the root window (or, rather, a window that sits on top of the root window).
    The manager handles the background image/color, root menu, window list, minimized app icons, file icons on the desktop (using Thunar libs).
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(exo-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(thunarx-3)
    - pkgconfig(x11)
    - libxfce4util-devel
setup      : |
    %configure
build      : |
    %make
install    : |-
    %make_install
