maintainer : streambinder
name       : switchboard-plug-onlineaccounts
version    : 2.0.1
release    : 5
source     :
    - https://github.com/elementary/switchboard-plug-onlineaccounts/archive/05b41fa33ca2bd09eedb27a9b94c4cf6e9a3e5b6.tar.gz : 45a29c2f582ca14fc79a77c2f2a17486ccc7780722fbd8241d942c44bc2f0e2f
license    : GPL-2.0
component  : desktop.pantheon
summary    : Switchboard online accounts plug
description: |
    Online Accounts plug for Switchboard which allows to enable online accounts sync.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(libgsignon-glib)
    - pkgconfig(libsignon-glib)
    - pkgconfig(rest-0.7)
    - pkgconfig(switchboard-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - glib2-devel
    - vala
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
