maintainer : algent-al
name       : procs
version    : 0.11.4
release    : 2
source     :
    - https://github.com/dalance/procs/archive/v0.11.4.tar.gz : 30a903374eb888b89cd43bbc19365aa24ef01b3588298ab246085dbe42c8e819
homepage   : https://github.com/dalance/procs
license    : MIT
component  : system.utils
summary    : A modern replacement for ps written in Rust
description: |
    procs is a modern replacement for ps written in Rust.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
    target/release/procs --completion bash
    target/release/procs --completion fish
    target/release/procs --completion zsh
install    : |
    install -Dm00755 target/release/procs -t $installdir/usr/bin/
    install -Dm00644 _procs -t $installdir/usr/share/zsh/site-functions
    install -Dm00644 procs.bash $installdir/usr/share/bash-completion/completions/procs
    install -Dm00644 procs.fish -t $installdir/usr/share/fish/vendor_completions.d
check      : |
    cargo test
