maintainer : streambinder
name       : pantheon-dock
version    : 0.0.1
release    : 2
source     :
    - https://github.com/elementary/dock/archive/9150dd81bc3741d76eefee54993d7fc89d8d0d03.tar.gz : 7c13e30799930f0e65b5385083ab352fa2ed1d51ac8b03c4f37d3bc7623fa2fb
license    : GPL-3.0
component  : desktop.pantheon
conflicts  :
    - plank
summary    : Pantheon dock
description: |
    Plank is meant to be the simplest dock on the planet.
    The goal is to provide just what a dock needs and absolutely nothing more.
    It is, however, a library which can be extended to create other dock programs with more advanced features.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gee-0.8)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(x11)
    - glib2-devel
    - gnome-common
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
# check      : |
#     %ninja_check