name: expositor

on: workflow_dispatch

jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Setup Go environment
        uses: actions/setup-go@v2-beta

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y parallel jq libcurl4-openssl-dev libgit2-28 libgit2-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          echo "PYTHONPATH=/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages" >> $GITHUB_ENV
          sudo ln -sf $(which python) /usr/bin/python3

      - name: Download and configure Solbuild
        run: |
          git clone https://github.com/getsolus/solbuild.git
          cd solbuild
          sudo make build install
          sudo solbuild init -u
          sudo mkdir /etc/solbuild
          sudo echo 'image = "main-x86_64"
          remove_repos = ["Solus"]
          add_repos = ["Local", "Theca", "Solus"]

          [repo.Local]
          uri = "'$GITHUB_WORKSPACE'/build"
          local = true
          autoindex = true

          [repo.Theca]
          uri = "https://unstable.solus.davidepucci.it/eopkg-index.xml.xz"

          [repo.Solus]
          uri = "https://mirrors.rit.edu/solus/packages/shannon/eopkg-index.xml.xz"
          ' | sudo tee -a /etc/solbuild/theca-x86_64.profile
          echo '[Packager]
          Name=Expositor
          Email=theca@davidepucci.it
          ' | sudo tee -a ~/.solus

      - name: Roll-out from unstable
        run: |
          make fetch release sync
        env:
          J: 5
          VARIANT: stable
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_THECA }}
