name: tester

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Setup Go environment
        uses: actions/setup-go@v2-beta

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y parallel jq libcurl4-openssl-dev libgit2-28 libgit2-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          echo "PYTHONPATH=/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages" >> $GITHUB_ENV
          sudo ln -sf $(which python) /usr/bin/python3

      - name: Download and configure Solbuild
        run: |
          git clone https://github.com/getsolus/solbuild.git
          cd solbuild
          sudo make build install
          sudo solbuild init -u
          sudo mkdir -p /etc/solbuild
          sudo echo 'image = "main-x86_64"
          remove_repos = ["Solus"]
          add_repos = ["Local", "Solus"]

          [repo.Local]
          uri = "'$GITHUB_WORKSPACE'/build"
          local = true
          autoindex = true

          [repo.Solus]
          uri = "https://mirrors.rit.edu/solus/packages/shannon/eopkg-index.xml.xz"
          ' | sudo tee -a /etc/solbuild/theca-x86_64.profile
          echo '[Packager]
          Name=Tester
          Email=theca@davidepucci.it
          ' | sudo tee -a ~/.solus

      - name: Build packages
        run: |
          make packages
        env:
          J: 5
          TMPFS: true
          SWEEP: true
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_THECA }}
