name: tester

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: silkeh/solus:solbuild
      options: --privileged -v /dev:/dev

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo eopkg ur
          sudo eopkg install -y parallel jq wget

      - name: Configure Solbuild
        run: |
          sudo solbuild init -u
          sudo mkdir -p /etc/solbuild
          sudo echo 'image = "main-x86_64"
          remove_repos = ["Solus"]
          add_repos = ["Local", "Solus"]

          [repo.Local]
          uri = "'$GITHUB_WORKSPACE'/build"
          local = true
          autoindex = true

          [repo.Solus]
          uri = "https://mirrors.rit.edu/solus/packages/shannon/eopkg-index.xml.xz"
          ' | sudo tee -a /etc/solbuild/theca-x86_64.profile
          echo '[Packager]
          Name=Tester
          Email=theca@davidepucci.it
          ' | sudo tee -a ~/.solus

      - name: Build packages
        run: |
          make packages
        env:
          J: 5
          TMPFS: true
          SWEEP: true
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_THECA }}
