maintainer : algent-al
name       : python-cairosvg
version    : 2.5.0
release    : 2
source     :
    - https://github.com/Kozea/CairoSVG/archive/2.5.0.tar.gz : 1560c66c119a1f74348293f484be4aef837b9691502c228e5e0f4824a0b6dfa5
homepage   : https://cairosvg.org/
license    : LGPL-3.0-or-later
component  : programming.python
summary    : CairoSVG is a SVG converter based on Cairo
description: |
    CairoSVG is a SVG converter based on Cairo. It can export SVG files to PDF, PostScript and PNG files.
builddeps  :
    - pytest-runner
    - pytest-isort
    - python-cairocffi
    - python-cssselect2
    - python-defusedxml
    - python-pillow
    - python-pytest-cov
    - python-pytest-flake8
rundeps    :
    - python-cairocffi
    - python-cssselect2
    - python-defusedxml
    - python-pillow
setup      : |
    cp -r cairosvg test_non_regression/cairosvg_reference/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
